name:               mirage2
version:            "0.0.0.0"
author:             Chan Beom Park
maintainer:         cbpark@gmail.com
license-file:       LICENSE
github:             cbpark/mirage2
category:           Physics
extra-source-files: csrc/*

ghc-options:        -Wall -Wcompat -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5

library:
  exposed-modules:
    - HEP.Data.AlphaS
    - HEP.Data.Constants
    - HEP.Data.Kinematics
    - HEP.Data.SUSY
    - HEP.Data.Quark
  source-dirs: lib
  cxx-sources: csrc/alphas.cc
  cxx-options: -g -O2 -m64 -Wall -Wextra -pedantic -fPIC
  extra-libraries:
    - LHAPDF
    - stdc++
  dependencies: math-functions

executables:
  mirage2:
    main: mirage2.hs
    source-dirs: src
    dependencies: mirage2

  mhiggs:
    main: mhiggs.hs
    source-dirs: src
    dependencies:
      - optparse-generic
      - vector
      - mirage2

  calcm0:
    main: calcm0.hs
    source-dirs: src
    dependencies:
      - vector
      - mirage2
