name:               mirage2
version:            "0.0.0.0"
author:             Chan Beom Park
maintainer:         cbpark@gmail.com
license-file:       LICENSE
github:             cbpark/mirage2
category:           Physics
extra-source-files: csrc/*

ghc-options:        -Wall -Wcompat -O2 -funbox-strict-fields
                    -fwrite-ide-info -hiedir=.hie

dependencies:
  - base >= 4.12.0.0 && < 5
  - optparse-generic

library:
  exposed-modules:
    - HEP.Data.AlphaS
    - HEP.Data.Constants
    - HEP.Data.Kinematics
    - HEP.Data.Interface
    - HEP.Data.SUSY
    - HEP.Data.Quark
  source-dirs: lib
  cxx-sources: csrc/alphas.cc
  cxx-options: -g -O2 -m64 -Wall -Wextra -pedantic -fPIC
  extra-libraries: [LHAPDF, stdc++]
  dependencies: math-functions

executables:
  mirage2:
    main: mirage2.hs
    source-dirs: src
    dependencies: mirage2

  ewsb:
    main: ewsb.hs
    source-dirs: src
    dependencies:
      - mirage2

  mhiggs: &higgs
    main: mhiggs.hs
    source-dirs: src
    dependencies: [vector, mirage2]

  finetuning_b:
    <<: *higgs
    main: finetuning_b.hs

  finetuning_mu:
    <<: *higgs
    main: finetuning_mu.hs

  calcm0_higgs:
    <<: *higgs
    main: calcm0_higgs.hs

  calcm0_stop:
    <<: *higgs
    main: calcm0_stop.hs

  calcm0_bmu:
    <<: *higgs
    main: calcm0_bmu.hs

  calcmu_higgs:
    <<: *higgs
    main: calcmu_higgs.hs
